; sol
#Include .\sol\basic.ahk
#Include .\sol\num.ahk
; spc
#Include .\spc\0.ahk
#Include .\spc\1.ahk
#Include .\spc\2.ahk
#Include .\spc\3.ahk
#Include .\spc\4.ahk
#Include .\spc\5.ahk
#Include .\spc\mouse.ahk
; muh
#Include .\muh\1.ahk
#Include .\muh\2.ahk
#Include .\muh\3.ahk
#Include .\muh\4.ahk
#Include .\muh\5.ahk
#Include .\muh\mouse.ahk