; SetTimer
#Include .\function\ime.ahk
#Include .\function\suspend.ahk
; fx
#Include .\function\fxAlwaysOnTop.ahk
#Include .\function\fxEdgeBookmark.ahk
#Include .\function\fxText.ahk
#Include .\function\fxPenMode.ahk
#Include .\function\fxPen.ahk
#Include .\function\fxToggleHkk.ahk
#Include .\function\plFxHotif.ahk
#Include .\function\plFxState.ahk
; group
#Include .\function\hnkX2\1.ahk
#Include .\function\hnkX2\2.ahk
#Include .\function\hnkX2\3.ahk
#Include .\function\hnkX2\4.ahk
#Include .\function\hnkX2\5.ahk