; x2
#Include .\x2\mouse.ahk
#Include .\x2\1.ahk
#Include .\x2\2.ahk
#Include .\x2\3.ahk
#Include .\x2\4.ahk
#Include .\x2\5.ahk
; hnk
#Include .\hnk\1.ahk
#Include .\hnk\2.ahk
#Include .\hnk\3.ahk
#Include .\hnk\4.ahk
#Include .\hnk\5.ahk
#Include .\hnk\mouse.ahk
; ctl
#Include .\ctl\3.ahk
#Include .\ctl\4.ahk
#Include .\ctl\5.ahk
; sft
#Include .\sft\1.ahk
#Include .\sft\2.ahk
#Include .\sft\5.ahk
; x1
#Include .\x1\mouse.ahk