#Include .\vscode\vscode.ahk
#Include .\youtube\youtube.ahk
#Include .\excel\excel.ahk
#Include .\chatgpt\chatgpt.ahk
#Include .\edge\edge.ahk
#Include .\vrew\vrew.ahk
#Include .\power\power.ahk
#Include .\pen\pen.ahk
#Include .\exp\exp.ahk
#Include .\hot\hot.ahk